name: Output Information
on: issues
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub Context
        run: |
            echo "${{ toJson(github) }}"
      - name: Output Event Name
        run: |
            echo "Event Name: ${{ github.event_name }}"
      - name: Output Repository Name
        run: |
            echo "Repository Name: ${{ github.repository }}"
      - name: Output Issue Title
        run: |
            echo "Issue Title: ${{ github.event.issue.title }}"